export const DASHBOARD = 'dashboard'
export const EXAMPLE = 'example'
export const AI = 'ai'
export const FRONTEND = 'frontend'
export const BITCOIN = 'bitcoin'
export const JAVASCRIPT = 'javascript'
export const NETWORK_PROTOCOL = 'networkProtocol'
export const ECMASCRIPT = 'ecmascript'
